// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/about" | "/admin" | "/admin/about" | "/admin/applications" | "/admin/applications/create" | "/admin/applications/settings" | "/admin/change-password" | "/admin/constituency" | "/admin/contact" | "/admin/legislative" | "/admin/login" | "/admin/media" | "/admin/news" | "/admin/post-creator" | "/admin/projects" | "/admin/users" | "/admin/volunteers" | "/applications/submit" | "/constituency" | "/contact" | "/gallery" | "/legislative" | "/news" | "/news/[id]" | "/projects" | "/projects/[id]" | "/sticker-generator" | "/support" | "/supporter-card" | "/volunteer"
type AppRouteHandlerRoutes = "/api/about" | "/api/auth/change-password" | "/api/auth/login" | "/api/legislative" | "/api/media" | "/api/news" | "/api/news/[id]" | "/api/news/admin" | "/api/projects" | "/api/setup" | "/api/stickers" | "/api/stickers/track" | "/api/users" | "/api/users/[id]"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin" | "/design/website" | "/sticker-generator/components/templates/design-system"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/about": {}
  "/admin": {}
  "/admin/about": {}
  "/admin/applications": {}
  "/admin/applications/create": {}
  "/admin/applications/settings": {}
  "/admin/change-password": {}
  "/admin/constituency": {}
  "/admin/contact": {}
  "/admin/legislative": {}
  "/admin/login": {}
  "/admin/media": {}
  "/admin/news": {}
  "/admin/post-creator": {}
  "/admin/projects": {}
  "/admin/users": {}
  "/admin/volunteers": {}
  "/api/about": {}
  "/api/auth/change-password": {}
  "/api/auth/login": {}
  "/api/legislative": {}
  "/api/media": {}
  "/api/news": {}
  "/api/news/[id]": { "id": string; }
  "/api/news/admin": {}
  "/api/projects": {}
  "/api/setup": {}
  "/api/stickers": {}
  "/api/stickers/track": {}
  "/api/users": {}
  "/api/users/[id]": { "id": string; }
  "/applications/submit": {}
  "/constituency": {}
  "/contact": {}
  "/design/website": {}
  "/gallery": {}
  "/legislative": {}
  "/news": {}
  "/news/[id]": { "id": string; }
  "/projects": {}
  "/projects/[id]": { "id": string; }
  "/sticker-generator": {}
  "/sticker-generator/components/templates/design-system": {}
  "/support": {}
  "/supporter-card": {}
  "/volunteer": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
  "/design/website": never
  "/sticker-generator/components/templates/design-system": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
