export const news = [
    {
        _id: '1',
        title: 'Hassan Hussain Sponsors Education for 30 Orphans',
        content: '<p>Hon. Hassan Shehu Hussain has launched a full sponsorship program for 30 orphaned children from his neighborhood. The comprehensive package covers school fees, uniforms, and educational materials at private schools, ensuring these vulnerable children have access to quality education and a brighter future.</p>',
        category: 'Education',
        imageUrl: '/assets/images/projects/edu-6/CHILDREN ORphan.jpg',
        publishDate: '2023-11-15T10:00:00Z',
        excerpt: 'Full sponsorship covering fees and uniforms for 30 orphans launched at Gama residence.',
    },
    {
        _id: '2',
        title: 'Hotoro Arewa Praises New Clinic and Classrooms',
        content: '<p>Residents of Hotoro Arewa have expressed deep gratitude to Hon. Hassan for the construction of a new Primary Health Care Clinic in Yandodo and a block of 6 classrooms in Ladanai. These infrastructure projects address critical needs in healthcare and education, significantly improving the quality of life for the community.</p>',
        category: 'Infrastructure',
        imageUrl: '/assets/images/projects/health-1/with pubic.jpg',
        publishDate: '2024-04-10T10:00:00Z',
        excerpt: 'Community celebrates new Yandodo Clinic and Ladanai classrooms.',
    },
    {
        _id: '3',
        title: 'Solar Boreholes Ease Water Crisis in Nassarawa',
        content: '<p>Amidst power outages, Hon. Hassan\'s installation of solar-powered boreholes across Hotoro, Haye, and other areas has been a lifeline. Constituents now have reliable access to clean water independent of the national grid, showcasing the impact of sustainable infrastructure.</p>',
        category: 'Agric & Water',
        imageUrl: '/assets/images/projects/elec-4/505854166_3178447675642520_353271535521781115_n.jpg',
        publishDate: '2025-01-20T10:00:00Z',
        excerpt: 'Solar boreholes provide reliable water access during power outages.',
    },
    {
        _id: '4',
        title: 'Empowerment Boost: Machines and Support',
        content: '<p>Continuing his massive empowerment drive, Hon. Hassan has distributed a new wave of support items including sewing machines, grinding machines, and motorcycles. This initiative is aimed at fostering self-reliance and boosting the local economy by equipping women and youth with the tools they need to succeed.</p>',
        category: 'Empowerment',
        imageUrl: '/assets/images/projects/emp-1/many sewing.jpg',
        publishDate: '2025-08-01T10:00:00Z',
        excerpt: 'Distribution of machines and motorcycles to boost local businesses.',
    },
    {
        _id: '5',
        title: 'Motion for Aminu Kano Hospital Rehabilitation',
        content: '<p>Hon. Hassan raised a critical motion on the floor of the House highlighting the severe shortage of heart surgeons and equipment at Aminu Kano Teaching Hospital. His advocacy has led to the setup of a parliamentary investigative committee to address these gaps and improve healthcare delivery.</p>',
        category: 'Legislative',
        imageUrl: '/assets/images/gallery/0-portraits-official/hon-standing-on-speaker-reading-book.jpg',
        publishDate: '2024-06-15T10:00:00Z',
        excerpt: 'Legislative action to address equipment and staff shortages at AKTH.',
    },
    {
        _id: '6',
        title: 'Bill for Federal Vocational College Advances',
        content: '<p>A bill sponsored by Hon. Hassan for the establishment of a Federal College of Vocational Skill Acquisition in Yankaba has passed its second reading. This legislation demonstrates his commitment to human capital development and equipping youth with practical skills for the future.</p>',
        category: 'Legislative',
        imageUrl: '/assets/images/gallery/0-portraits-official/public-pres.jpg',
        publishDate: '2024-02-07T10:00:00Z',
        excerpt: 'Bill for Yankaba Vocational College passes second reading.',
    },
    {
        _id: '7',
        title: 'Condemnation of Tudun Biri Bombing',
        content: '<p>Hon. Hassan has strongly condemned the tragic bombing incident at Tudun Biri. In a passionate address, he called for immediate justice for the victims and urged the government to take decisive measures to prevent such occurrences in the future.</p>',
        category: 'Legislative',
        imageUrl: '/assets/images/gallery/0-portraits-official/potraitn.jpg',
        publishDate: '2023-12-05T10:00:00Z',
        excerpt: 'Strong call for justice and prevention following tragic incident.',
    },
    {
        _id: '8',
        title: 'Continuity and Gratitude: Voices from Nassarawa',
        content: '<p>"4+4 Insha Allahu" echoes across Nassarawa as residents share testimonials of Hon. Hassan\'s impact. From accessible leadership to tangible infrastructure like street lights and transformers, the community stands united in their support for his continued service.</p>',
        category: 'Politics',
        imageUrl: '/assets/images/projects/road-1/476629181_600759826039972_3454055431456145227_n.jpg',
        publishDate: '2024-09-01T10:00:00Z',
        excerpt: 'Community testimonials highlight infrastructure and leadership impact.',
    }
];
